plugins { id 'org.springframework.boot' }

dependencies {
    implementation project(':common')

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'

    // MyBatis + JDBC(HikariCP는 spring-jdbc가 기본으로 사용)
    implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:3.0.5'
    runtimeOnly 'org.mariadb.jdbc:mariadb-java-client'

    // Kafka
    implementation 'org.springframework.kafka:spring-kafka'

    // JWT (로직은 추후 추가)
    implementation 'io.jsonwebtoken:jjwt-api:0.12.6'
    runtimeOnly  'io.jsonwebtoken:jjwt-impl:0.12.6'
    runtimeOnly  'io.jsonwebtoken:jjwt-jackson:0.12.6'

    // Swagger / OpenAPI UI
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.14'
}
